import { redirect } from 'next/navigation'
import { getSession } from '@/lib/auth/guard'
import { portalLang } from '@/lib/portal-lang'
import PortalHeader from '@/components/PortalHeader'
export const dynamic = 'force-dynamic'
export default async function Login({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
 const sp = await searchParams; const lang = await portalLang(); const ko = lang === 'ko'
 if (await getSession()) redirect('/workspace')
 return <div className="portal"><PortalHeader lang={lang}/><main className="login-hero"><div className="login-intro"><p className="portal-eyebrow">FRANKONIA CUSTOMER MANAGEMENT</p><h1>{ko ? '고객과 기술을 연결하는' : 'CONNECTING CUSTOMERS.'}<br/><em>{ko ? 'FRANKONIA' : 'EMPOWERING'} </em>{ko ? '워크스페이스' : 'YOUR WORK.'}</h1><p>{ko ? '고객 커뮤니케이션부터 챔버 견적까지. Frankonia의 업무를 하나의 공간에서 시작하세요.' : 'From customer communication to chamber quotations. Start your work in one Frankonia workspace.'}</p><div className="hero-caption">EMC TEST SOLUTIONS · ENGINEERED IN GERMANY SINCE 1987</div></div><section className="login-panel"><p className="portal-eyebrow">{ko ? '인가된 사용자 전용' : 'AUTHORIZED PERSONNEL'}</p><h2>{ko ? '로그인' : 'Sign in'}</h2><p className="portal-muted">{ko ? '기존 FCM 계정으로 로그인하세요.' : 'Use your existing FCM account.'}</p>{sp.error && <p className="portal-error" role="alert">{sp.error === 'unavailable' ? (ko ? '로컬 서버 연결을 확인한 뒤 다시 시도하세요.' : 'Check your local server connection and try again.') : (ko ? 'ID 또는 비밀번호를 확인해 주세요.' : 'Check your ID and password and try again.')}</p>}<form action="/entry/login" method="post"><input type="hidden" name="lang" value={lang}/><label htmlFor="loginId">ID</label><input id="loginId" name="loginId" autoComplete="username" required maxLength={128}/><label htmlFor="password">{ko ? '비밀번호' : 'Password'}</label><input id="password" name="password" type="password" autoComplete="current-password" required maxLength={1024}/><button className="portal-primary">{ko ? '로그인' : 'Sign in'} <span>→</span></button></form><p className="login-footnote">{ko ? '로그인 후 Customer Management 또는 Calculation Table을 선택할 수 있습니다.' : 'After signing in, choose Customer Management or Calculation Table.'}</p></section></main><footer className="portal-footer"><span>FRANKONIA · CUSTOMER MANAGEMENT</span><span>{ko ? '안전한 로컬 워크스페이스' : 'YOUR SECURE LOCAL WORKSPACE'}</span></footer></div>
}
